-- Create knowledge_cards table
CREATE TABLE IF NOT EXISTS public.knowledge_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    category TEXT NOT NULL,
    keywords TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(post_id)
);

-- Migration: Add user_id column if table already exists
-- ALTER TABLE public.knowledge_cards ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Enable RLS (Row Level Security)
ALTER TABLE public.knowledge_cards ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for everyone
CREATE POLICY "Enable read access for all users" ON public.knowledge_cards
    FOR SELECT USING (true);

-- Create policy to allow insert access for authenticated users (or specific roles if needed)
-- For now, allowing authenticated users to insert (since the API will handle the logic)
CREATE POLICY "Enable insert for authenticated users" ON public.knowledge_cards
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy to allow delete only for the card owner
CREATE POLICY "Enable delete for card owner" ON public.knowledge_cards
    FOR DELETE USING (auth.uid() = user_id);
